const express = require('express')
const router = express.Router()
const { registerUser, LoginUser, getMe, updateProfile } = require('../controllers/userController')
const { protect } = require('../middleware/authMiddleware')
const { getAllSteps, createStep, updateStep, getAllContacts, createContact, getSingleStep, getAllWeightLossFAQ, singleWeightLossFAQ, createWeightLossFAQ, editWeightLossFAQ, deleteWeightLossFAQ, createGeneralFAQ, getAllGeneralFAQ, singleGeneralFAQ, editGeneralFAQ, deleteGeneralFAQ, createService, getAllService, singleService, editService, deleteService } = require('../controllers/adminController')
const { getAllBlogs, createBlog, editBlog, getSingleBlog, deleteBlog } = require('../controllers/blogController')

router.get('/all-steps', getAllSteps)
router.post('/create-step', createStep)
router.get('/step/:id', protect, getSingleStep)
router.put('/step/:step', protect, updateStep)
router.get('/contacts', protect, getAllContacts)
router.post('/contact/create', createContact)
router.get('/weightlossfaq', getAllWeightLossFAQ)
router.get('/weightlossfaq/:id', singleWeightLossFAQ)
router.post('/weightlossfaq', protect, createWeightLossFAQ)
router.put('/weightlossfaq/:id', protect, editWeightLossFAQ)
router.delete('/weightlossfaq/:id', protect, deleteWeightLossFAQ)
router.post('/generalfaq', protect, createGeneralFAQ)
router.get('/generalfaq', getAllGeneralFAQ)
router.get('/generalfaq/:id', singleGeneralFAQ)
router.put('/generalfaq/:id', protect, editGeneralFAQ)
router.delete('/generalfaq/:id', protect, deleteGeneralFAQ)
router.post('/service', protect, createService)
router.get('/service', getAllService)
router.get('/service/:id', singleService)
router.put('/service/:id', protect, editService)
router.delete('/service/:id', protect, deleteService)
router.get('/blogs', getAllBlogs)
router.get('/blog/:id', getSingleBlog)
router.post('/blog', protect, createBlog)
router.put('/blog/:id', protect, editBlog)
router.delete('/blog/:id', protect, deleteBlog)


module.exports = router